plugins = {
    "AddEntriesTableUp": "Добавить записи выше в таблице",
    "AddEntriesTableEnd": "Добавить записи в конец таблицы",
    "ChangeLevelStructureRight": "Сдвинуть уровень вправо",
    "ChangeLevelStructureLeft": "Сдвинуть уровень влево",
    "MoveRowUp": "Сдвинуть строчку выше",
    "MoveRowDown": "Сдвинуть строчку ниже",
    "CreateTemplate": "Создать шаблон",
    "CreatePlanFromTemplate": "Создать план из шаблона",
    "AffixingPointPlacementOKSOnMap": "Проставления точки размещения ОКС на карте",
    "OpenExonTab": "Открыть вкладку с Exon",
    "AutomaticFillingNewProjectPlan": "Автоматического наполнения нового плана проекта",
    "CreateExonUserPlugin": "Создать учётную запись в EXON",
    "AddParticipantToExonPlugin": "Добавить участника в проект EXON",
    "CreateExonConstructionObjectPlugin": "Создание ОКС в EXON",
    "RunReportFromConfigurationTable": "Запуск отчетов из конфигурационной таблицы",
    "AddOrganizationToExonProjectPlugin": "Добавить организацию в проект EXON",
    "AddingProjectsToFavorites": '''Добавление проектов в "Избранное"''',
    "RunReportAndSendMailPlugin": "Запуск отчетов и отправка по почте",
    "RunReportAndSendMailCommand": "Запуск отчетов и отправка по почте для команды",
    "SaveSurveyListPlugin": "Создать опрос-лист",
    "OpenSurveyListPlugin": "Открыть дашборд опрос-листа",
    "IdentifyCardToOpenPlugin": "Определить карточку для открытия",
    "CreatReportWithSignaturesConstructionProjectsCommand": "Сформировать отчет для ОКС с подписями",
    "FillXmlFieldInMaintenanceRequestCommand": "Заполнение поля XML в запросе на обслуживание",
    "ExonTokenQuery": "Запрос токена Exon",
    "CreateExonUserCommand": "Создать пользовательскую команду Exon",
    "CreateExonConstructionObjectCommand": 'Команда "Создать объект построения экзона"',
    "RunReportFromConfigurationTableCommand": "Команда «Запустить отчет из таблицы конфигурации»",
    "AutomaticFillingNewProjectPlanCommand": "Команда автоматического заполнения нового плана проекта",
    "IdentifyCardToOpenCommand": "Определите карту для команды открытия",
    "AddOrganizationToExonProjectCommand": "Добавить организацию в команду проекта Exon",
    "AddingProjectsToFavoritesCommand": "Команда добавления проектов в избранное",
    "AddParticipantToExonCommand": "Добавить участника в команду Exon",
    "CreateSurveyListDashboardCommand": "Команда создания панели мониторинга списка опросов"
}

plugin_types = {
    'RegistryService.INFO': 'Бэкенд',
    'LoggerRecordCommand.INFO': 'Фронтенд'
}